suite: devkit_distribute
category: functional

devkit_distribute:
root_path: ${root_path}
ips_list: ${ips_list}
user: ${user}
port: ${port}
pkey_file: ${pkey_file}
pkey_password: ${pkey_password}
devkit_ip: ${devkit_ip}
devkit_port: ${devkit_port}
devkit_user: ${devkit_user}
devkit_password: ${devkit_password}
applications: ${applications}
duration: ${duration}
git_path: ${git_path}

