USER = "user"
PKEY = "pkey"
PASSWORD = "password"
SCANNER = "scanner"
BUILDER = "builder"
EXECUTOR = "executor"
DEVKIT = "devkit"
MACHINE = "machine"
DEPENDENCY_FILE = "devkitdependencies.tar.gz"
DEPENDENCY_DIR = "devkitdependencies"

INSTRUCTION = "instruction"
