server:
  port: 10037

scriptConfigCn: /data/software/cloudTest/script/compatibility_testing.conf
scriptConfigEn: /data/software/cloudTest/script/compatibility_testing_EN.conf
tempDir: /data/software/cloudTest/tmp
deployIp: 172.39.92.22
uploadFileDir: /data/software/cloudTest/data
appId: com.huawei.icopenlab.website
appKey: ENC(avto39VXGCZudTEfU1DQjuou0INTVQpvA75GmdwZzIA=)
mqsTopic: T_OPENLAB_TEST_PROJECT_MESSAGE
mqsUrl: https://apigw-beta.huawei.com/api/mqs/message/beta
clamdIp : localhost
clamdPort : 3310
performanceTestUrl : http://%s:8095/rest/v1/cloud-test/lab
appIdUat: com.huawei.icopenlab.website
appKeyUat: ENC(avto39VXGCZudTEfU1DQjuou0INTVQpvA75GmdwZzIA=)
mqsTopicUat: T_OPENLAB_TEST_PROJECT_MESSAGE
mqsUrlUat: https://mqs/message/beta
kunpengServiceUrl: https://kunpengcommunity/cloudbase/auth
teeCodeServerUrl : http://1111/code-server/
dgCodeServerUrl: http://1111/code-server/

crypto:
  aes-default-key: ENC(x2P5OjvjSqOMi9AGhKR70e1o5XLRd9XuUdfZPfFiL2VeQ5RTs498/f85N4moRzeBbr1to42juDgqnsuw8Wn9ykc9WrpdZ2AiwYdV09O9600=)
  aes-default-aad: openlab
  aes-cipher-mode: AES/GCM/PKCS5Padding
logging:
  level:
    root: debug