suite: devkit_distributor
category: functional

devkit_distribute:
root_path: /home/z30027893/Workspace/devkit-pipeline/component/DevKitDistributor/devkit_distributor
ips_list: 
user: root
port: 22
pkey_file: 
pkey_password: 
devkit_ip: 
devkit_port: 8086
devkit_user: devadmin
devkit_password: admin100
applications: 
duration: 10
git_path: 
jmeter_command: "bash jmetser.sh -t -n /hoem/jskldfs/"

